version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: products
    ports:
      - "3307:3306"
    networks:
      - product_network

  product-api-1:
    build:
      context: .
    container_name: product-api-1
    ports:
      - "8081:8080"
    environment:
      - INSTANCE_NAME=API-1
    networks:
      - product_network

  product-api-2:
    build:
      context: .
    container_name: product-api-2
    ports:
      - "8082:8080"
    environment:
      - INSTANCE_NAME=API-2
    networks:
      - product_network

  product-api-3:
    build:
      context: .
    container_name: product-api-3
    ports:
      - "8083:8080"
    environment:
      - INSTANCE_NAME=API-3
    networks:
      - product_network

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - product-api-1
      - product-api-2
      - product-api-3
    networks:
      - product_network

networks:
  product_network:
    driver: bridge


