name: Deploy to EC2

on:
  push:
    branches:
      - main  # main 브랜치에 push 될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy jar to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa \
            docker-compose.yml \
            ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/

      - name: Deploy to EC2 via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            docker rm -f product-api || true
            docker rmi miiniiidi/product-api:latest || true
            docker pull miiniiidi/product-api:latest

            docker run -d --name product-api -p 8080:8080 \
              -e SPRING_PROFILES_ACTIVE=prod \
              -e SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }} \
              -e SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }} \
              -e SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }} \
              miiniiidi/product-api:latest
          EOF

